import { Injectable, signal, computed } from '@angular/core';
import { Appointment } from '../models';

@Injectable({ providedIn: 'root' })
export class BookingService {
  // Public appointments array (includes mock + real bookings)
  private _appointments = signal<Appointment[]>([]);

  readonly appointments = this._appointments.asReadonly();
  readonly count = computed(() => this._appointments().length);

  addAppointment(appt: Omit<Appointment, 'id' | 'status' | 'revenue'>): Appointment {
    const newAppt: Appointment = {
      ...appt,
      id: 'appt-' + Date.now(),
      status: 'scheduled',
      revenue: 0, // set by fee from doctor
    };
    this._appointments.update(list => [...list, newAppt]);
    return newAppt;
  }

  /** Merge mock data generated by DataService */
  seedAppointments(appointments: Appointment[]): void {
    this._appointments.set(appointments);
  }

  getAll(): Appointment[] {
    return this._appointments();
  }

  getByDate(date: Date): Appointment[] {
    return this._appointments().filter(a => {
      const d = new Date(a.date);
      return d.toDateString() === date.toDateString();
    });
  }

  /** Returns slots already booked for a doctor on a specific date */
  getBookedSlots(doctorId: string, date: Date): string[] {
    return this._appointments()
      .filter(a => {
        const d = new Date(a.date);
        return a.doctorId === doctorId && d.toDateString() === date.toDateString();
      })
      .map(a => a.timeSlot);
  }
}
